### ISSUE TITLE
Add auto-remove brace for double character stored as one

### ISSUE THREAD

**Issue by 92rick** [HobbitDur/ShumiTranslator#1]
Could you remember to fix the braces, please? Thank ♥

**Comment by HobbitDur** [comment]
The idea is to remove all doubel chracter in bracket by real 2 characters. Take more space but is more readable when translating

**Comment by 92rick** [comment]
And also try to change special characters like "{x0e37}"

**Comment by HobbitDur** [comment]
Done in commit https://github.com/HobbitDur/ShumiTranslator/commit/24a8c84968b7ccdaa597aacd1137819d1e959d2d
for the variable part, it will be done later (it's an other problematic)
